#!/bin/bash -l

#$ -P sachgrp
#$ -N job_1_split_pdf_from_raw_source
#$ -m bea
#$ -pe omp 16

export PYTHONUNBUFFERED=1

module load miniconda
conda activate /projectnb/sachgrp/apgupta/case_law_semantic_search_pipeline/sach_semantic_env

# Just change the state name and the country name in the input variable for this
python3 job_1_split_pdfs_from_raw_source.py "/projectnb/sachgrp/prathamk/CaseLaw/USA/Maine/" "/projectnb/sachgrp/apgupta/Case Law Data/USA/Maine"